# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-16 13:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsCase',
            fields=[
                ('name', models.CharField(max_length=150)),
                ('elastic_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('img_preview', models.CharField(max_length=300)),
                ('follow_new_feed', models.BooleanField(default=True)),
                ('creation_date', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='newscase',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='explora.Profile'),
        ),
    ]
