# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-11 14:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('social_auth', '0005_auto_20160727_2333'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsCase',
            fields=[
                ('name', models.CharField(max_length=150)),
                ('elastic_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('img_preview', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='social_auth.UserSocialAuth')),
            ],
        ),
        migrations.AddField(
            model_name='newscase',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='explora.Profile'),
        ),
    ]
