# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-16 19:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explora', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newscase',
            name='creation_date',
            field=models.DateField(),
        ),
    ]
