# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-12 19:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explora', '0002_auto_20170111_1908'),
    ]

    operations = [
        migrations.AddField(
            model_name='newscase',
            name='case_open',
            field=models.BooleanField(default=True),
        ),
    ]
