# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-12 20:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('explora', '0003_newscase_case_open'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newscase',
            old_name='case_open',
            new_name='follow_new_feed',
        ),
    ]
